#!/usr/bin/python3

import argparse
from pathlib import Path

INI_SECTION="[{}]\n"
INI_LINE="{}={}\n"

def main():
    return

if __name__ == '__main__':
    parser = argparse.ArgumentParser(prog='json-to-ini',description='Takes a json. Spits out an ini',epilog='See readme for further details.')
    parser.add_argument('-f','--file', help='Path to file',required=True)
    parser.add_argument('-s','--section', help='Name of top level INI section')
    args = parser.parse_args()
    main(args)